FROM alpine:latest

RUN apk add --no-cache \
    curl \
    git \
    libc6-compat \
    libstdc++ \
    gcc \
    g++ \
    musl-dev

ARG HUGO_VERSION=0.139.0

RUN curl -L -o /tmp/hugo.tar.gz \
    https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz && \
    tar -xzf /tmp/hugo.tar.gz -C /usr/local/bin hugo && \
    rm /tmp/hugo.tar.gz && \
    hugo version

WORKDIR /site